language: python
python:
- '3.6'
- '3.7'
cache: pip
env:
  - SKLEARN=0.20.x
  - SKLEARN=0.23.x

install:
- pip install -e .
script:
- python nyoka/tests/test_import.py
- python nyoka/tests/_install_dependencies.py
- python nyoka/tests/_validateSchema.py
- python nyoka/tests/test_skl_to_pmml_UnitTest.py
- python nyoka/tests/test_xgboost_to_pmml_UnitTest.py
- python nyoka/tests/test_lgbm_to_pmml_UnitTest.py
- python nyoka/tests/test_statsmodels_to_pmml_UnitTest.py

after_success:
- py.test  --cov-report term --cov=nyoka/
- codecov
notifications:
  email:
    recipients:
    - maintainer@nyoka.org
    on_success: never
    on_failure: always
